# Generated by Django 4.1.10 on 2023-08-30 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=1, unique=True)),
                ('mumuki_id', models.IntegerField()),
                ('full_text', models.TextField()),
                ('kw1', models.TextField()),
                ('kw2', models.TextField()),
                ('kw3', models.TextField()),
                ('kw4', models.TextField()),
                ('kw5', models.TextField()),
                ('ok_sent1', models.TextField()),
                ('ok_sent2', models.TextField()),
                ('ok_sent3', models.TextField()),
                ('rej_sent1', models.TextField()),
                ('rej_sent2', models.TextField()),
                ('rej_sent3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LastTagged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_id', models.IntegerField(default=1)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mumuki_id', models.IntegerField(default=1)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('semantic_score', models.IntegerField(default=3)),
                ('content_score', models.IntegerField(default=3)),
                ('completeness_score', models.IntegerField(default=3)),
                ('summary_score', models.IntegerField(default=3)),
                ('comparison_score', models.IntegerField(default=3)),
                ('annotator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
