# Generated by Django 4.1.10 on 2023-08-31 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_tagger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lasttagged',
            name='group',
            field=models.IntegerField(default=1),
        ),
    ]
